### ISSUE TITLE
访问emby异常

### ISSUE THREAD

**Issue by klaxonz** [monlor/docker-xiaoya#104]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
容器启动一天了，看日志元数据已经下载完了，alist 可以正常访问，但是访问emby报错，看日志好像是 sqlite 数据库文件占用了。

**重现步骤**
使用 docker compose 安装，等待alist启动和元数据下载完成后，访问emby失败。

**预期行为**

**截图**
<img width="1590" alt="image" src="https://github.com/monlor/docker-xiaoya/assets/33013259/d74d904c-dd1a-4862-8410-79f64156ffb0">

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**

**emby 日志**
``` txt
Info SqliteItemRepository: Opening sqlite connection to /config/data/library.db
Info SqliteItemRepository: Default journal_mode for /config/data/library.db is wal
Info SqliteItemRepository: PRAGMA cache_size=-524288
Info SqliteItemRepository: PRAGMA page_size=4096
Info SqliteItemRepository: PRAGMA foreign_keys=1
Info SqliteItemRepository: Result of setting SQLITE_DBCONFIG_DQS_DDL to 0 is 0
Info SqliteItemRepository: Result of setting SQLITE_DBCONFIG_DQS_DML to 0 is 0
Info SqliteItemRepository: Init Complete
Error Main: Error in appHost.Init
        *** Error Report ***
        Version: 4.8.8.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 6.1.0-20-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT
        Framework: .NET 6.0.25
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 12
        Data path: /config
        Application path: /system
        SQLitePCL.pretty.SQLiteException: Busy: database is locked
        SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
           at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
           at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
           at SQLitePCL.pretty.StatementImpl.MoveNext()
           at Emby.Sqlite.SqliteExtensions.ExecuteQuery(IStatement This)+MoveNext()
           at Emby.Server.Implementations.Data.SqliteItemRepository.GetNamedValueTypeId(IDatabaseConnection db, String name)
           at Emby.Server.Implementations.Data.SqliteItemRepository.GetNamedValue(String name)
           at Emby.Server.Implementations.Configuration.ServerConfigurationManager.LoadNamedConfiguration(String key)
           at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
           at Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfiguration(String key)
           at MediaBrowser.Common.Configuration.ConfigurationManagerExtensions.GetConfiguration[T](IConfigurationManager manager, String key)
           at Emby.Server.Implementations.Configuration.ServerConfigurationManager.UpdateTranscodingTempPath()
           at Emby.Server.Implementations.ApplicationHost.FindParts()
           at Emby.Server.Implementations.ApplicationHost.Init()
           at EmbyServer.HostedService.StartAsync(CancellationToken cancellationToken)
        Source: SQLitePCL.pretty
        TargetSite: Void CheckOk(SQLitePCLEx.sqlite3, Int32)

Info Main: Shutdown complete
```
**metadata 日志**
``` txt
06/11 19:37:09 [NOTICE] Download complete: /media/temp/pikpak.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c76f4d|OK  |   4.1MiB/s|/media/temp/pikpak.mp4

Status Legend:
(OK):download completed.
Extracting Emby media...

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Common KVM processor (F61),ASM)

Scanning the drive for archives:
1 file, 35999219160 bytes (34 GiB)

Extracting archive: /media/temp/all.mp4
--
Path = /media/temp/all.mp4
Type = 7z
Offset = 370745
Physical Size = 35998848415
Headers Size = 8897151
Method = LZMA2:24
Solid = +
Blocks = 22

Everything is Ok

Folders: 34363
Files: 864706
Size:       45748897719
Compressed: 35999219160

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Common KVM processor (F61),ASM)

Scanning the drive for archives:
1 file, 15168649913 bytes (15 GiB)

Extracting archive: /media/temp/pikpak.mp4
--
Path = /media/temp/pikpak.mp4
Type = 7z
Offset = 370745
Physical Size = 15168279168
Headers Size = 2974843
Method = LZMA2:26
Solid = +
Blocks = 5

Everything is Ok

Folders: 13456
Files: 312730
Size:       20640872458
Compressed: 15168649913
启动定时更新Emby媒体数据任务...
Complete.
```

**Comment by monlor** [comment]
一般情况下不可能出现数据被占用的情况，请检查服务部署问题

**Comment by klaxonz** [comment]
看起来是因为我volume挂载的是samba目录，有可能是因为samba权限问题导致

**Comment by lson-lee** [comment]
救，我遇到了同样的问题，我使用 docker compose up 的方法启动的，alist、元数据都没问题了，访问 emby 就是楼主的这个截图，embyserver docker 镜像的日志没有报错_(:з」∠)_（有个很奇怪的是 emby server 的镜像我尝试 bash 进去看一下但是每次都会卡住，不知道是否相关）
