### ISSUE TITLE
[BUG]: emby无法访问

### ISSUE THREAD

**Issue by kittyzero520** [monlor/docker-xiaoya#251]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [ ] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [ ] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

通过Docker Compose 一键部署服务，alist 5678正常，cha'kaemby提示502错误，查看日志一直显示检查alist连通性...

等待配置数据下载完成...

等待媒体数据下载完成...
![alist](https://github.com/user-attachments/assets/52b0bda4-22d0-46c7-8904-25a415ebf1eb)
![emby](https://github.com/user-attachments/assets/f06fef12-5b81-47a7-a41a-8eb752be8785)

### 设备 (请填写以下信息)

其他（在其他信息中补充）

### 其他信息

实体机安装飞牛OS，Docker Compose 一键部署服务

**Comment by kittyzero520** [comment]
services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - /vol1/1000/小雅/xiaoya:/data
    ports:
      - "5678:5678"
      - "2588:2588"
      - "2589:2589"
    env_file:
      - /vol1/1000/小雅/env
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata:latest
    env_file:
      - /vol1/1000/小雅/env
    volumes:
      - /vol1/1000/小雅/xiaoya:/etc/xiaoya
      - /vol1/1000/小雅/media:/media/xiaoya
      - /vol1/1000/小雅/config:/media/config
      - /vol1/1000/小雅/cache:/media/config/cache
      - /vol1/1000/小雅/meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  emby:
    image: ghcr.io/monlor/xiaoya-embyserver:latest
    env_file:
      - /vol1/1000/小雅/env
    depends_on:
      - metadata
      - alist
    volumes:
      - /vol1/1000/小雅/media:/media
      - /vol1/1000/小雅/config:/config
      - /vol1/1000/小雅/cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache:

**Comment by kittyzero520** [comment]
![Uploading alist更新数据显示最新.png…]()

**Comment by Rhythmicc** [comment]
俺也一样，emby一直502，等待配置文件下载。。

**Comment by M78-Monster** [comment]
应该是目录映射的问题。检查一下emby容器`/media`目录所映射的宿主机目录下有没有输出`emby_media_finished`。
![image](https://github.com/user-attachments/assets/e87416b8-40a3-45c5-b0db-c91d41c6d245)

- [ ]

**Comment by evancyz** [comment]
一样的问题，我看配置文件里没有这个文件，这个怎么处理呢

**Comment by duchong001** [comment]
我这里遇到的问题有点不一样， embyserver容器能正常启动，但是访问页面就报错：

![Image](https://github.com/user-attachments/assets/be8813fb-a088-4c4f-b06f-4e07be9655f2)

**Comment by duchong001** [comment]
运行日志：
`Info App: Sqlite: 1 - no such column: Album in "select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,P

Error TaskManager: Error in IsHidden

        *** Error Report ***

        Version: 4.8.10.0

        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3

        Operating system: Linux version 6.6.38-trim (root@debian) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #80 SMP PREEMPT_DYNAMIC Tue Dec 10 20:4

        Framework: .NET 6.0.31

        OS/Process: x64/x64

        Runtime: system/System.Private.CoreLib.dll

        Processor count: 4

        Data path: /config

        Application path: /system

        SQLitePCL.pretty.SQLiteException: Error: no such column: Album - select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,SortName,RunTimeTicks,Size,Container,DateCreated,DateModified,guid,ParentId,IsInMixedFolder,DateLastSaved,LockedFields,OriginalTitle,CriticRating,SeriesName,Album,AlbumId,SeriesId,PresentationUniqueKey,Tagline,ProviderIds,Images,ProductionLocations,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,Status,DisplayOrder,ThreeDFormat,ChannelNumber,RemoteTrailers,SortIndexNumber,SortParentIndexNumber,IndexNumberEnd,IsPublic from MediaItems where Id=15569

        SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.

           at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, ReadOnlySpan`1& tail)

           at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)

           at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemByIdInternal(IDatabaseConnection db, Int64 id)

           at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemById(Int64 id)

           at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Int64 id)

           at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()

           at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()

           at MediaBrowser.Controller.Entities.UserRootFolder.GetItemsInternal(InternalItemsQuery query)

           at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)

           at MediaBrowser.Controller.Entities.Folder.GetChildren(InternalItemsQuery query)

           at Emby.Providers.Markers.MarkerScheduledTask.IsTaskEnabled()

           at Emby.Providers.Markers.MarkerScheduledTask.get_IsEnabled()

           at Emby.Providers.Markers.MarkerScheduledTask.get_IsHidden()

           at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.LoadTriggerSettings()

        Source: SQLitePCL.pretty

        TargetSite: SQLitePCL.pretty.IStatement PrepareStatement(System.String, System.ReadOnlySpan`1[System.Byte] ByRef)



Info TaskManager: Daily trigger for Rotate log file set to fire at 02/25/2025 00:00:00, which is 54.2662163 minutes from now.

Info TaskManager: Queueing task HardwareDetectionScheduledTask

Info TaskManager: Executing Hardware Detection

Info App: ServerId: cf5b029bcf2244a9a159e0c382ab0f15

Info FfmpegManager: ProcessRun 'ffmpeg -hide_banner -version' Execute: /bin/ffmpeg -hide_banner -version

Info App: Starting entry point Emby.Server.Implementations.Networking.RemoteAddressEntryPoint

Info App: Loading data from /config/data/wan.dat

Info App: Entry point completed: Emby.Server.Implementations.Networking.RemoteAddressEntryPoint. Duration: 0.0087866 seconds

Info App: Starting entry point Emby.Server.Connect.ConnectEntryPoint

Info App: Loading data from /config/data/connect.txt

Info App: Entry point completed: Emby.Server.Connect.ConnectEntryPoint. Duration: 0.004961 seconds

Info App: Core startup complete

Info App: Starting entry point AutoCollections.ServerEntryPoint

Info App: Entry point completed: AutoCollections.ServerEntryPoint. Duration: 0.0003141 seconds

Info App: Starting entry point Emby.Security.PluginSecurityManager

Info App: Entry point completed: Emby.Security.PluginSecurityManager. Duration: 0.0001996 seconds

Info App: Starting entry point Emby.Server.CinemaMode.IntrosEntryPoint

Info App: Entry point completed: Emby.Server.CinemaMode.IntrosEntryPoint. Duration: 0.0009989 seconds

Info App: Starting entry point Emby.Webhooks.MigrationEntryPoint

Info App: Entry point completed: Emby.Webhooks.MigrationEntryPoint. Duration: 0.008881 seconds

Info App: Starting entry point MovieDb.Security.PluginStartup

Info App: Entry point completed: MovieDb.Security.PluginStartup. Duration: 0.0037699 seconds

Info App: Starting entry point NfoMetadata.EntryPoint

Info App: Entry point completed: NfoMetadata.EntryPoint. Duration: 0.0035965 seconds

Info App: Starting entry point Emby.Server.Implementations.Udp.UdpServerEntryPoint

Info App: Entry point completed: Emby.Server.Implementations.Udp.UdpServerEntryPoint. Duration: 0.003159 seconds

Info App: Starting entry point Emby.Server.Implementations.Playlists.PlaylistUpgradeEntryPoint

Info App: Entry point completed: Emby.Server.Implementations.Playlists.PlaylistUpgradeEntryPoint. Duration: 0.006755 seconds

Info App: Starting entry point Emby.Server.Implementations.Library.DeviceAccessEntryPoint

Info App: Entry point completed: Emby.Server.Implementations.Library.DeviceAccessEntryPoint. Duration: 0.002815 seconds

Info App: Starting entry point Emby.Server.Implementations.IO.LibraryMonitorStartup

Info App: Sqlite: 1 - no such column: Album in "select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,P

Error App: Error in Emby.Server.Implementations.IO.LibraryMonitorStartup

        *** Error Report ***

        Version: 4.8.10.0

        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3

        Operating system: Linux version 6.6.38-trim (root@debian) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #80 SMP PREEMPT_DYNAMIC Tue Dec 10 20:4

        Framework: .NET 6.0.31

        OS/Process: x64/x64

        Runtime: system/System.Private.CoreLib.dll

        Processor count: 4

        Data path: /config

        Application path: /system

        SQLitePCL.pretty.SQLiteException: Error: no such column: Album - select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,SortName,RunTimeTicks,Size,Container,DateCreated,DateModified,guid,ParentId,IsInMixedFolder,DateLastSaved,LockedFields,OriginalTitle,CriticRating,SeriesName,Album,AlbumId,SeriesId,PresentationUniqueKey,Tagline,ProviderIds,Images,ProductionLocations,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,Status,DisplayOrder,ThreeDFormat,ChannelNumber,RemoteTrailers,SortIndexNumber,SortParentIndexNumber,IndexNumberEnd,IsPublic from MediaItems where Id=15569

        SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.

           at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, ReadOnlySpan`1& tail)

           at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)

           at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemByIdInternal(IDatabaseConnection db, Int64 id)

           at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemById(Int64 id)

           at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Int64 id)

           at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()

           at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()

           at MediaBrowser.Controller.Entities.UserRootFolder.GetItemsInternal(InternalItemsQuery query)

           at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)

           at MediaBrowser.Controller.Entities.Folder.GetChildren(InternalItemsQuery query)

           at Emby.Server.Implementations.IO.LibraryMonitor.Start()

           at Emby.Server.Implementations.IO.LibraryMonitorStartup.Run()

           at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup)

        Source: SQLitePCL.pretty

        TargetSite: SQLitePCL.pretty.IStatement PrepareStatement(System.String, System.ReadOnlySpan`1[System.Byte] ByRef)



Info App: Entry point completed: Emby.Server.Implementations.IO.LibraryMonitorStartup. Duration: 0.7618424 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint. Duration: 0.0038947 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.KeepServerAwake

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.KeepServerAwake. Duration: 0.0003757 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier. Duration: 0.0044514 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.ServerEventNotifier

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.ServerEventNotifier. Duration: 0.0079693 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.StartupWizard

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.StartupWizard. Duration: 0.0030945 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.SystemEvents

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.SystemEvents. Duration: 0.0032261 seconds

Info App: Starting entry point Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier

Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier. Duration: 0.0003117 seconds

Info App: Starting entry point Emby.Server.Implementations.Channels.ChannelsEntryPoint

Info App: Entry point completed: Emby.Server.Implementations.Channels.ChannelsEntryPoint. Duration: 0.0064418 seconds

Info App: Starting entry point Emby.LiveTV.EntryPoint

Info LiveTV: Loading live tv data from /config/data/livetv/timers

Info App: Entry point completed: Emby.LiveTV.EntryPoint. Duration: 0.0276083 seconds

Info App: Starting entry point Emby.LiveTV.RecordingNotifier

Info App: Entry point completed: Emby.LiveTV.RecordingNotifier. Duration: 0.0064745 seconds

Info App: Starting entry point Emby.ActivityLog.ActivityLogEntryPoint

Info App: Entry point completed: Emby.ActivityLog.ActivityLogEntryPoint. Duration: 0.0076797 seconds

Info App: Starting entry point Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint

Info App: Entry point completed: Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint. Duration: 0.0043411 seconds

Info App: Starting entry point Emby.Notifications.NotificationManagerEntryPoint

Info Notifications: Registering event nofitier Emby Server User Notifications

Info App: Entry point completed: Emby.Notifications.NotificationManagerEntryPoint. Duration: 0.0292046 seconds

Info App: Starting entry point Emby.Server.Sync.SyncNotificationEntryPoint

Info App: Entry point completed: Emby.Server.Sync.SyncNotificationEntryPoint. Duration: 0.0072378 seconds

Info App: Starting entry point EmbyServer.Windows.LoopUtilEntryPoint

Info App: Entry point completed: EmbyServer.Windows.LoopUtilEntryPoint. Duration: 0.0007748 seconds

Info App: All entry points have started`

**Comment by wyp-g** [comment]
> 运行日志： `Info App: Sqlite: 1 - no such column: Album in "select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,P
> 
> Error TaskManager: Error in IsHidden
> 
> ```
>     *** Error Report ***
> 
>     Version: 4.8.10.0
> 
>     Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
> 
>     Operating system: Linux version 6.6.38-trim (root@debian) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #80 SMP PREEMPT_DYNAMIC Tue Dec 10 20:4
> 
>     Framework: .NET 6.0.31
> 
>     OS/Process: x64/x64
> 
>     Runtime: system/System.Private.CoreLib.dll
> 
>     Processor count: 4
> 
>     Data path: /config
> 
>     Application path: /system
> 
>     SQLitePCL.pretty.SQLiteException: Error: no such column: Album - select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,SortName,RunTimeTicks,Size,Container,DateCreated,DateModified,guid,ParentId,IsInMixedFolder,DateLastSaved,LockedFields,OriginalTitle,CriticRating,SeriesName,Album,AlbumId,SeriesId,PresentationUniqueKey,Tagline,ProviderIds,Images,ProductionLocations,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,Status,DisplayOrder,ThreeDFormat,ChannelNumber,RemoteTrailers,SortIndexNumber,SortParentIndexNumber,IndexNumberEnd,IsPublic from MediaItems where Id=15569
> 
>     SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
> 
>        at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, ReadOnlySpan`1& tail)
> 
>        at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
> 
>        at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemByIdInternal(IDatabaseConnection db, Int64 id)
> 
>        at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemById(Int64 id)
> 
>        at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Int64 id)
> 
>        at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
> 
>        at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
> 
>        at MediaBrowser.Controller.Entities.UserRootFolder.GetItemsInternal(InternalItemsQuery query)
> 
>        at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
> 
>        at MediaBrowser.Controller.Entities.Folder.GetChildren(InternalItemsQuery query)
> 
>        at Emby.Providers.Markers.MarkerScheduledTask.IsTaskEnabled()
> 
>        at Emby.Providers.Markers.MarkerScheduledTask.get_IsEnabled()
> 
>        at Emby.Providers.Markers.MarkerScheduledTask.get_IsHidden()
> 
>        at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.LoadTriggerSettings()
> 
>     Source: SQLitePCL.pretty
> 
>     TargetSite: SQLitePCL.pretty.IStatement PrepareStatement(System.String, System.ReadOnlySpan`1[System.Byte] ByRef)
> ```
> 
> Info TaskManager: Daily trigger for Rotate log file set to fire at 02/25/2025 00:00:00, which is 54.2662163 minutes from now.
> 
> Info TaskManager: Queueing task HardwareDetectionScheduledTask
> 
> Info TaskManager: Executing Hardware Detection
> 
> Info App: ServerId: cf5b029bcf2244a9a159e0c382ab0f15
> 
> Info FfmpegManager: ProcessRun 'ffmpeg -hide_banner -version' Execute: /bin/ffmpeg -hide_banner -version
> 
> Info App: Starting entry point Emby.Server.Implementations.Networking.RemoteAddressEntryPoint
> 
> Info App: Loading data from /config/data/wan.dat
> 
> Info App: Entry point completed: Emby.Server.Implementations.Networking.RemoteAddressEntryPoint. Duration: 0.0087866 seconds
> 
> Info App: Starting entry point Emby.Server.Connect.ConnectEntryPoint
> 
> Info App: Loading data from /config/data/connect.txt
> 
> Info App: Entry point completed: Emby.Server.Connect.ConnectEntryPoint. Duration: 0.004961 seconds
> 
> Info App: Core startup complete
> 
> Info App: Starting entry point AutoCollections.ServerEntryPoint
> 
> Info App: Entry point completed: AutoCollections.ServerEntryPoint. Duration: 0.0003141 seconds
> 
> Info App: Starting entry point Emby.Security.PluginSecurityManager
> 
> Info App: Entry point completed: Emby.Security.PluginSecurityManager. Duration: 0.0001996 seconds
> 
> Info App: Starting entry point Emby.Server.CinemaMode.IntrosEntryPoint
> 
> Info App: Entry point completed: Emby.Server.CinemaMode.IntrosEntryPoint. Duration: 0.0009989 seconds
> 
> Info App: Starting entry point Emby.Webhooks.MigrationEntryPoint
> 
> Info App: Entry point completed: Emby.Webhooks.MigrationEntryPoint. Duration: 0.008881 seconds
> 
> Info App: Starting entry point MovieDb.Security.PluginStartup
> 
> Info App: Entry point completed: MovieDb.Security.PluginStartup. Duration: 0.0037699 seconds
> 
> Info App: Starting entry point NfoMetadata.EntryPoint
> 
> Info App: Entry point completed: NfoMetadata.EntryPoint. Duration: 0.0035965 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.Udp.UdpServerEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Implementations.Udp.UdpServerEntryPoint. Duration: 0.003159 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.Playlists.PlaylistUpgradeEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Implementations.Playlists.PlaylistUpgradeEntryPoint. Duration: 0.006755 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.Library.DeviceAccessEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Implementations.Library.DeviceAccessEntryPoint. Duration: 0.002815 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.IO.LibraryMonitorStartup
> 
> Info App: Sqlite: 1 - no such column: Album in "select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,P
> 
> Error App: Error in Emby.Server.Implementations.IO.LibraryMonitorStartup
> 
> ```
>     *** Error Report ***
> 
>     Version: 4.8.10.0
> 
>     Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
> 
>     Operating system: Linux version 6.6.38-trim (root@debian) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #80 SMP PREEMPT_DYNAMIC Tue Dec 10 20:4
> 
>     Framework: .NET 6.0.31
> 
>     OS/Process: x64/x64
> 
>     Runtime: system/System.Private.CoreLib.dll
> 
>     Processor count: 4
> 
>     Data path: /config
> 
>     Application path: /system
> 
>     SQLitePCL.pretty.SQLiteException: Error: no such column: Album - select type,Id,StartDate,EndDate,IsMovie,IsSeries,IsKids,IsSports,IsNews,IsRepeat,IsNew,IsPremiere,IsLive,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,SortName,RunTimeTicks,Size,Container,DateCreated,DateModified,guid,ParentId,IsInMixedFolder,DateLastSaved,LockedFields,OriginalTitle,CriticRating,SeriesName,Album,AlbumId,SeriesId,PresentationUniqueKey,Tagline,ProviderIds,Images,ProductionLocations,TotalBitrate,ExtraType,ExternalId,SeriesPresentationUniqueKey,Status,DisplayOrder,ThreeDFormat,ChannelNumber,RemoteTrailers,SortIndexNumber,SortParentIndexNumber,IndexNumberEnd,IsPublic from MediaItems where Id=15569
> 
>     SQLitePCL.pretty.SQLiteException: Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
> 
>        at SQLitePCL.pretty.SQLiteDatabaseConnection.PrepareStatement(String sql, ReadOnlySpan`1& tail)
> 
>        at SQLitePCL.pretty.DatabaseConnection.PrepareStatement(IDatabaseConnection This, String sql)
> 
>        at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemByIdInternal(IDatabaseConnection db, Int64 id)
> 
>        at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemById(Int64 id)
> 
>        at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Int64 id)
> 
>        at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
> 
>        at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
> 
>        at MediaBrowser.Controller.Entities.UserRootFolder.GetItemsInternal(InternalItemsQuery query)
> 
>        at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
> 
>        at MediaBrowser.Controller.Entities.Folder.GetChildren(InternalItemsQuery query)
> 
>        at Emby.Server.Implementations.IO.LibraryMonitor.Start()
> 
>        at Emby.Server.Implementations.IO.LibraryMonitorStartup.Run()
> 
>        at Emby.Server.Implementations.ApplicationHost.RunEntryPoints(IEnumerable`1 entryPoints, Boolean isBeforeStartup)
> 
>     Source: SQLitePCL.pretty
> 
>     TargetSite: SQLitePCL.pretty.IStatement PrepareStatement(System.String, System.ReadOnlySpan`1[System.Byte] ByRef)
> ```
> 
> Info App: Entry point completed: Emby.Server.Implementations.IO.LibraryMonitorStartup. Duration: 0.7618424 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.AutomaticRestartEntryPoint. Duration: 0.0038947 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.KeepServerAwake
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.KeepServerAwake. Duration: 0.0003757 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.LibraryChangedNotifier. Duration: 0.0044514 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.ServerEventNotifier
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.ServerEventNotifier. Duration: 0.0079693 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.StartupWizard
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.StartupWizard. Duration: 0.0030945 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.SystemEvents
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.SystemEvents. Duration: 0.0032261 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier
> 
> Info App: Entry point completed: Emby.Server.Implementations.EntryPoints.UserDataChangeNotifier. Duration: 0.0003117 seconds
> 
> Info App: Starting entry point Emby.Server.Implementations.Channels.ChannelsEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Implementations.Channels.ChannelsEntryPoint. Duration: 0.0064418 seconds
> 
> Info App: Starting entry point Emby.LiveTV.EntryPoint
> 
> Info LiveTV: Loading live tv data from /config/data/livetv/timers
> 
> Info App: Entry point completed: Emby.LiveTV.EntryPoint. Duration: 0.0276083 seconds
> 
> Info App: Starting entry point Emby.LiveTV.RecordingNotifier
> 
> Info App: Entry point completed: Emby.LiveTV.RecordingNotifier. Duration: 0.0064745 seconds
> 
> Info App: Starting entry point Emby.ActivityLog.ActivityLogEntryPoint
> 
> Info App: Entry point completed: Emby.ActivityLog.ActivityLogEntryPoint. Duration: 0.0076797 seconds
> 
> Info App: Starting entry point Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint
> 
> Info App: Entry point completed: Emby.Server.MediaEncoding.Api.EncodingManagerEntryPoint. Duration: 0.0043411 seconds
> 
> Info App: Starting entry point Emby.Notifications.NotificationManagerEntryPoint
> 
> Info Notifications: Registering event nofitier Emby Server User Notifications
> 
> Info App: Entry point completed: Emby.Notifications.NotificationManagerEntryPoint. Duration: 0.0292046 seconds
> 
> Info App: Starting entry point Emby.Server.Sync.SyncNotificationEntryPoint
> 
> Info App: Entry point completed: Emby.Server.Sync.SyncNotificationEntryPoint. Duration: 0.0072378 seconds
> 
> Info App: Starting entry point EmbyServer.Windows.LoopUtilEntryPoint
> 
> Info App: Entry point completed: EmbyServer.Windows.LoopUtilEntryPoint. Duration: 0.0007748 seconds
> 
> Info App: All entry points have started`

+1，我也出现了这个报错，sqlite找不到字段，

**Comment by hotwa** [comment]
解决了吗

**Comment by Censwin** [comment]
> 我这里遇到的问题有点不一样， embyserver容器能正常启动，但是访问页面就报错：
> 
> ![Image](https://github.com/user-attachments/assets/be8813fb-a088-4c4f-b06f-4e07be9655f2)

同问解决了吗？一样的问题，折腾2天了

**Comment by bref0** [comment]
Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown.
